FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel

RUN : \
    && apt-get update \
    && apt-get install build-essential cmake git -y \
    && apt-get install libopenblas-dev liblapack-dev -y \
    && apt-get install libx11-dev libgtk-3-dev libgl1-mesa-glx libglib2.0-0 -y \
    && git clone https://github.com/davisking/dlib.git \
    && cd dlib && python3 setup.py install \
    && cd .. && rm -rf dlib
